### ISSUE TITLE
[Feature] Fishing rod speed configuration

### ISSUE THREAD

**Issue by LinsaFTW** [kernitus/BukkitOldCombatMechanics#149]
Hi , i noticed the 1.9 Rod has a range of 8 blocks and the 1.8 rod has a range of 12 blocks.

This is annoying uhc players on my server.

Can you add a configuration to change the Rod Velocity?

Example:

```yml
# The rod will go until it reachs the defined amount of blocks
RodSpeed:
  Enabled: true
  worlds: []
# The amount of blocks you want the rod to travel before it falls down
  Speed: 12
```

Thanks :) This is really annoying UHC Players , hope you can add it :)
