### ISSUE TITLE
Projectile Randomness & Multishot

### ISSUE THREAD

**Issue by ArtelGG** [kernitus/BukkitOldCombatMechanics#331]
## Info
The `disable-projectile-randomness` doesn't seem to ignore/handle/implement the "Multishot" enchantment properly.

- **Server version:** PaperSpigot 1.14.4-b148
- **OldCombatMechanics version:** 1.7.4-BETA
- **Server log file:** N/A
- **OldCombatMechanics config file:** N/A

## Problem Description
> The Multishot arrows are all being placed in the centre, while this isn't a negative thing perse, it does kind of defeat the purpose of this enchant and I believe there should be an option to make all 3 shots directly centred (like how they are with this "issue") or shoot in a "centred" or "derandomized" cone.

**Comment by I-Al-Istannen** [comment]
Multishot is crossbow only IIRC. This did not exist in 1.8. What mechanic would you prefer for those?
A config option to leave it alone? Center them? Provide your own offset?

**Comment by ArtelGG** [comment]
All 3 of those options sound good.

**A (very poor) example of the implementation in the configuration file:**
```
disable-projectile-randomness:
  # This is to remove projectile randomness while firing arrows with a bow
  # This is actually a very old feature and has been in the game for quite some time
  enabled: false
  worlds: []
  multishot:
    # Setting this to "true" will result in vanilla behaviour for *only* multishot crossbows.
    ignore: false
    # This setting allows you to modify how spread out the additional projectiles from multishot are.
    #   If 'ignore' is false, the projectiles will be derandomized, and 'spread' will be applied.
    # Setting this to 0 will make all 3 shots land in the same place.
    # Setting this to <insert default spread here> will give you the vanilla spread.
    # Setting this to or above <insert> may cause problems, for example, arrows coming out of the player's FOV.
    spread: <insert default spread here>
```
