### ISSUE TITLE
Cant enabled off hand

### ISSUE THREAD

**Issue by LielXD** [kernitus/BukkitOldCombatMechanics#377]
i enabled the off hand on the config and its didnt work.
i dont have any idea.

Config
https://pastebin.com/GjeryjxM
Log File:
https://hastebin.com/peduyukoze

**Comment by Rayzr522** [comment]
Please post your config to pastebin.com, along with a full logfile from your server.

**Comment by LielXD** [comment]
Config
https://pastebin.com/GjeryjxM
Log File:
https://hastebin.com/peduyukoze

**Comment by Rayzr522** [comment]
@LielXD you currently have your config set to disable the offhand in two worlds. however, the indentation of the `worlds` key in the `disable-offhand` section of the config appears to be incorrect. please ensure the indentation is fixed before reloading the config and testing again.

**Comment by LielXD** [comment]
i was change it to "survival" and its dont worked

**Comment by Rayzr522** [comment]
So in the world named `survival`, you still can't use your offhand? Did you fix your config to have correct indentation?

**Comment by LielXD** [comment]
CONFIG:
https://pastebin.com/dxRKvyd7
LOG:
https://hastebin.com/qequsigufo

**Comment by Rayzr522** [comment]
As I said previously, your config is *still* broken. You have this:

```yaml
disable-attack-cooldown:
  # This is to disable the attack cooldown
  enabled: true
 worlds: [survival]
  # What to set the attack speed to. Default for 1.9 is 4, at least 16 is needed for no cooldown.
  generic-attack-speed: 24
```

but it should be this:

```yaml
disable-attack-cooldown:
  # This is to disable the attack cooldown
  enabled: true
  worlds: [survival]
  # What to set the attack speed to. Default for 1.9 is 4, at least 16 is needed for no cooldown.
  generic-attack-speed: 24
```

note the indentation before the `worlds: [survival]` -- indentation in YAML files is *critical*
