### ISSUE TITLE
Messages for enderpearl cooldowns.

### ISSUE THREAD

**Issue by Agaloth** [kernitus/BukkitOldCombatMechanics#468]
As the title says, it would be cool to have something like the thing below.

```
disable-enderpearl-cooldown:
  # Disables enderpearl cooldown
  enabled: true
  worlds: []
  # The cooldown, in seconds
  cooldown: 15
  message: &b%cooldown placeholder thing maybe% left before using your enderpearl again...
```
