### ISSUE TITLE
Message for disabled crafting

### ISSUE THREAD

**Issue by AfkF24** [kernitus/BukkitOldCombatMechanics#471]
## Problem
Similar to #468, there should be a message informing the player that the specified item is disabled for crafting.

## Proposed solution
```yaml
disable-crafting:
  enabled: true
  worlds: []
  denied: [chest torch]
  denied-message: "%item% is disabled from being crafted."
```
