### ISSUE TITLE
BOW BOOSTING LIKE 1.8/12

### ISSUE THREAD

**Issue by alexeses** [kernitus/BukkitOldCombatMechanics#515]
Hello!

I'm using the latest version of OCM and all correct, however, the server is 1.16.5 and unfortunately the Minecraft has made internal changes in the push with the bow, called "bow booting" a pvp technique that many users use. For example, this video I attach https://imgur.com/a/SjS2pFK.

Can the OCM do it in minecraft 1.16.x versions? You can try it and it really is very complicated to push yourself with the bow, the arrow must come out of the player's hitbox and it really becomes complicated and tedious for users. 

Is there any option in the OCM or any way to do it?

**Comment by alexeses** [comment]
Actually, OCM has an option to disable it, 

```
disable-bow-boost:
  # This is to stop players from boosting themselves forward by hitting themselves.
  # while running with a punch II arrow from their bow
  # This module simply stops them from hitting themselves with arrows entirely
  enabled: false
  worlds: []
```

But in the new versions, Bow Booting is really impossible to do and very complicated. Couldn't you put it similar to older versions like 1.8-1.12, as far as I understand, it was removed in 1.13. Many servers are running on the latest version of Minecraft and lack this amazing feature.
