### ISSUE TITLE
Enderpearl isnt working properly

### ISSUE THREAD

**Issue by mariagomezjs** [kernitus/BukkitOldCombatMechanics#562]
## Information
* Server Version: Spigot 1.12.2
* OldCombatMechanics version: 1.9.0
* Server Log File: none
* OldCombatMechanics config file: default

## Problem Description
Enderpearl isnt working properly with default configuration, users who use enderpearls, they are supposed to take damage (5 dmg / 2.5 hearts). I know that this config exist:
```
projectile-knockback:
  enabled: true
  worlds: []
  damage:
    snowball: 0.0001
    egg: 0.0001
    ender_pearl: 0.0001 <---
```
But if I modify this one, it will hurt to someone who is hit by that enderpearl aswell, this means both players will get the dmg, instead of the one that is throwing it.

### To Reproduce
1. Download the plugin
2. Put in the plugin folder, with default config
3. Try to use enderpearl in survival mode
