### ISSUE TITLE
Toggle "set modeset" message

### ISSUE THREAD

**Issue by CheckMarvin** [kernitus/BukkitOldCombatMechanics#714]
## Information

* Server Version: Purpur 1.20.1

* OldCombatMechanics version: 2.0.1

* Server Log File: 
<details><summary>Server Log</summary>
  
``` console

```
</details>

* OldCombatMechanics config file: 
<details><summary>config.yml</summary>
  
``` yaml
modesets:
  # These modesets are lists of modules that are enabled for a player in that mode.
  # Modules not listed in any modeset are assumed to always be available.
  # You can create as many modesets as you like by adding a new key and corresponding list.
  # When in PvP, the modeset of the attacker is checked first.
  # If not PvP, the modeset of the defending entity is checked.
  # Of course, the module must also be enabled in its own config section.
  # Sample below has modules enabled for "old" combat modeset and disabled for "new" combat modeset
  old:
  - disable-attack-cooldown
  - disable-sword-sweep
  - disable-offhand
  - old-tool-damage
  - sword-blocking
  - shield-damage-reduction
  - old-golden-apples
  - old-player-knockback
  - old-player-regen
  - old-armour-strength
  - old-potion-effects
  - old-critical-hits

worlds:
  # These are the modesets available in each world.
  # If player has no modeset when moving worlds they'll be assigned first mode in list,
  # unless the mode from the world they are coming from is also available in the new world.
  # Worlds not specified below will have all modesets available.
  world:
  - old
  world_nether:
  - old
  world_the_end:
  - old
# old_world: ["old"]
# brave_new_world: ["new"]

mode-messages:
  # Messages used when changing player mode
  mode-status: '&bYour current modeset is: &7%s'
  message-usage: '&eYou can use &c/ocm mode <modeset> [player] &eto change modeset'
  invalid-modeset: '&cPlease specify a valid modeset!'
  invalid-player: '&cPlease specify a valid player!'
  mode-set: '&2Set modeset to &7%s'
```
</details>

### To Reproduce
 
1. You must have 2 worlds on your server
2. Switch from one world to the other first time after server restart

### Expected Behaviour

This message should not appear. I wish there is an option to enable / disable the message. Reason at the bottom.
![image](https://github.com/kernitus/BukkitOldCombatMechanics/assets/132604732/0bda9170-a55f-43e9-8513-c9e1edd7f923)

### Actual Behaviour

In chat this message appears:
![image](https://github.com/kernitus/BukkitOldCombatMechanics/assets/132604732/0bda9170-a55f-43e9-8513-c9e1edd7f923)

Why do I report this problem?
I have a minigame server with many worlds. Every time i change my world I get this message. It is a message, which I don't whant to show up. I whish there is a config option to toggle this message: "enable-modeset-message: false". I would be very happy if you solve this :)
