### ISSUE TITLE
disable specific worlds

### ISSUE THREAD

**Issue by davi-fonto** [kernitus/BukkitOldCombatMechanics#738]
hi, i have a server with multiple gamemodes (survival, hardcore and minigames). Is it possible to use this plugin with old 1.8 combat only in specific worlds (minigames worlds) and use the modern combat (1.9 onwards) in survival and hardcore worlds?

**Comment by SrBedrock** [comment]
yes, inside config.yml:

```yaml
modesets:
  # Modesets are lists of modules that are enabled for a player in that mode.
  # Modules not listed in any modeset are assumed to always be available.
  # You can create, remove, and rename as many modesets as you like by modifying the list below.
  # When in PvP, the modeset of the attacker is checked first.
  # If not PvP, the modeset of the defending entity is checked.
  # Of course, the module must also be enabled in its own config section.
  # Sample below has modules enabled for "old" combat modeset and disabled for "new" combat modeset
  # PlaceholderAPI: %ocm_modeset%
  old:
    - "disable-attack-cooldown"
    - "disable-sword-sweep"
    - "disable-offhand"
    - "old-tool-damage"
    - "sword-blocking"
    - "shield-damage-reduction"
    - "old-golden-apples"
    - "old-player-knockback"
    - "old-player-regen"
    - "old-armour-strength"
    - "old-potion-effects"
    - "old-critical-hits"
  new: [ ]

worlds:
  # These are the modesets available in each world.
  # If player has no modeset when moving worlds they'll be assigned first mode in list,
  # unless the mode from the world they are coming from is also available in the new world.
  # Worlds not specified below will have all modesets available.
  survival_world: [ "new" ] 
  hardcore_world: [ "new" ] 
  minigame_world: [ "old" ]
```
