### ISSUE TITLE
Old PVP

### ISSUE THREAD

**Issue by Souheii** [kernitus/BukkitOldCombatMechanics#741]
Hi ! Could you tell me how to make sure that players are forced into old mode pvp?

**Comment by SrBedrock** [comment]
@Souheii inside config.yml

```yaml
modesets:
  old:
    - "disable-attack-cooldown"
    - "disable-sword-sweep"
    - "disable-offhand"
    - "old-tool-damage"
    - "sword-blocking"
    - "shield-damage-reduction"
    - "old-golden-apples"
    - "old-player-knockback"
    - "old-player-regen"
    - "old-armour-strength"
    - "old-potion-effects"
    - "old-critical-hits"
  new: [ ]

worlds:
  world: [ "old"
  world_nether: [ "old"]
  world_the_end: [ "old" ]
  # old_world: ["old"]
  # brave_new_world: ["old"]
 ```
