### ISSUE TITLE
Chorus fruits tp randomly inside blocks

### ISSUE THREAD

**Issue by Bafy78** [kernitus/BukkitOldCombatMechanics#748]
## Information

* Server Version: 1.21.1

* OldCombatMechanics version: dev build 238

* Server Log File: 
<details><summary>Server Log</summary>
  
``` console
nothing interesting
```
</details>

* OldCombatMechanics config file: 
<details><summary>config.yml</summary>
  
``` yaml
chorus-fruit:
  # This makes the chorus fruit behaviour configurable
  enabled: true
  # The maximum distance the fruit can teleport the player. This a PER AXIS value, so this outlines a cube with
  # 2 * max-teleportation-distance as the side length
  # Vanilla default is 8.
  # Setting this to 0 disables chorus fruit teleport.
  # Setting this to a value greater than 8 MIGHT CAUSE CONFLICTS with bukkit's internal anti cheat
  # and *potentially* any other anti-cheat you use. Please make sure this is not an issue before increasing
  # this value.
  max-teleportation-distance: 5
  # Whether to prevent eating the fruit completely. This also prevents the teleportation.
  prevent-eating: false
  # The saturation value of the chorus fruit.
  # Vanilla default is 2.4
  saturation-value: 2.4
  # The hunger value of the chorus fruit.
  # Vanilla default is 4 (2 bars)
  hunger-value: 4
```
</details>

## Problem Description

The chorus fruits, when the module is enabled, don't work properly at all and tp inside blocks.

### To Reproduce
 
1. Enable the chorus fruits module
2. Change the teleportation distance value to anything other than the default (8)
3. Eat chorus fruits

### Expected Behaviour

You would be tped randomly above blocks in places where you can stand, in the radius

### Actual Behaviour

You are tped anywhere, inside full blocks.
